### ISSUE TITLE
write tests

### ISSUE THREAD

**Issue by fernandogelin** [compbiocore/refchef#3]
Here we are using the pytest framework. Feel free to use `UnitTests` as well.

**Comment by fernandogelin** [comment]
@andrew-leith regarding tests for the functions that retrieve files, I was thinking about creating an S3 bucket with some small files and have a simple yaml that points to that. And for the github functions, once we refactor the code to use GitHub API we can test for the right response.

**Comment by andrew-leith** [comment]
Sounds good to me.
