### ISSUE TITLE
problems with more than 1 index file

### ISSUE THREAD

**Issue by JRWallace** [compbiocore/refchef#35]
Right now it seems that refchef assumes that each reference genome will have a single index file associated with it. However, different bioinformatics programs create their own index files (bwa, bowtie2, and samtools each create their own index files, for example). For example, if I run a new yaml file with:
```
  levels:
    indices:
    - component: bowtie2_index
```
and then run another yaml with this:
```
  levels:
    indices:
    - component: bwa_index
```
The bowtie2_index is overwritten by the bwa_index in master.yaml and refchef-menu. Is it possible to allow each reference genome to have an infinite number of indexes associated with it as long as the `component` entry is unique?

**Comment by ashokrags** [comment]
This is a more generic problem. Refchef updates key:values  within a the reference if it exists rather than appending to it. Could be related to  the  `update ` function in utils.py
